### ISSUE TITLE
9447 CTF nobranch writeup

### ISSUE THREAD

**Issue by abpolym** [pwning/public-writeup#1]
Will you release a writeup for nobranch :)?

**Comment by percontation** [comment]
Yeah, it's almost ready :)

**Comment by percontation** [comment]
Fixed in 28bceec5dbf

**Comment by abpolym** [comment]
\o/ awesome

**Comment by abpolym** [comment]
Btw! Is there a doom6 (9447-2014) writeup from you guys somewhere? Can't find any.

**Comment by percontation** [comment]
Nah, we don't have that one, sorry.
