### ISSUE TITLE
114514 in MoP meaning

### ISSUE THREAD

**Issue by publicqi** [pwning/public-writeup#15]
It's really a meme/punchline on the Chinese internet. 114514 has the same pronunciation in Mandarin as "Okay! Come on!" in Japanese, and this is a famous line in one specific Japanese gay porn.

https://twitter.com/fox_1999/status/675702681952915456?lang=en

**Comment by georgegegege111** [comment]
u dumbfk, that is japanese, 114 is i i yo which is okay, 514 is ko i yo
